Repository Open-Earth-Foundation/CityCatalyst, pull requests merged in 2024-12, with the labels that each got.

#945 fix(ui): adds validation for new password input
  app/src/app/[lng]/auth/update-password/page.tsx
Labels: bug

#951 Fix/add padding to ask ai btn
  app/src/components/ChatBot/chat-popover.tsx
Labels: ui

#950 feat: adds circle flag component and locode extraction function
  app/src/components/Tabs/my-inventories-tab.tsx
Labels: bug, ui

#952 resolves null error
  app/src/components/Tabs/my-inventories-tab.tsx
Labels: bug

#956 fix(api): only allow connecting one source per GPC reference number
  app/package-lock.json
  app/src/backend/DataSourceService.ts
Labels: bug, dependencies, javascript, api, korbit-code-analysis

#958 fix(ui): connected third party data not being shown in MI
  app/src/app/[lng]/[inventory]/data/[step]/[subsector]/page.tsx
  app/src/services/api.ts
Labels: bug, javascript, ui, korbit-code-analysis

#953 fix(ui): resolves checkmark bug for all population inputs
  app/src/components/steps/add-population-data-step.tsx
  app/src/components/steps/chekmark.tsx
Labels: bug, ui

#964 fix(ui): navbar and chat assistant not rendering
  app/src/components/HomePage/HomePage.tsx
Labels: bug, korbit-code-analysis

#963 Fix Data rendering issue on multi year charts
  app/src/app/[lng]/[inventory]/InventoryResultTab/EmissionBySectorChart.tsx
  app/src/app/[lng]/[inventory]/InventoryResultTab/EmissionBySectorTable.tsx
  app/src/app/[lng]/[inventory]/InventoryResultTab/index.tsx
Labels: korbit-code-analysis

#918 bug: [ON-2881] deleteUserCityCascade
  app/migrations/20241121140052-inventory__alter__inventory_city__cascade.cjs
  app/src/app/api/v0/city/[city]/route.ts
  app/src/components/Modals/delete-city-modal.tsx
  app/src/components/password-input.tsx
  app/src/i18n/locales/de/settings.json
  app/src/i18n/locales/en/settings.json
  app/src/i18n/locales/es/settings.json
  app/src/i18n/locales/pt/settings.json
Labels: korbit-code-analysis

#966 fix(api): ON-2989 delete InventoryValue after last ActivityValue
  app/src/app/api/v0/inventory/[inventory]/activity-value/[id]/route.ts
  app/src/backend/ActivityService.ts
  app/src/components/Modals/delete-activity-modal.tsx
  app/src/models/InventoryValue.ts
  app/src/services/api.ts
Labels: korbit-code-analysis

#967 fix(api): count all InventoryValues with a source as third party
  app/src/backend/ECRFDownloadService.ts
  app/src/backend/InventoryProgressService.ts
Labels: korbit-code-analysis

#968 Fix/on 2975 deleted data not reflecting in progress
  app/src/app/[lng]/[inventory]/InventoryResultTab/EmissionBySectorChart.tsx
  app/src/app/[lng]/[inventory]/data/[step]/[subsector]/page.tsx
  app/src/app/[lng]/[inventory]/data/[step]/page.tsx
  app/src/app/api/v0/inventory/[inventory]/value/subsector/[subsector]/route.ts
  app/src/backend/InventoryProgressService.ts
  app/src/components/Cards/SectorCard.tsx
  app/src/components/Cards/SubSectorCard.tsx
  app/src/components/Cards/add-data-card.tsx
  app/src/components/Tabs/Activity/activity-tab.tsx
  app/src/services/api.ts
  app/src/util/constants.ts
  app/src/util/helpers.ts
  app/src/util/types.ts
Labels: korbit-code-analysis

#971 fix(api): load InventoryValues in emissions by scope
  app/src/app/api/v0/inventory/[inventory]/results/[sectorName]/route.ts
  app/src/app/api/v0/inventory/[inventory]/results/route.ts
  app/src/backend/ResultsService.ts
  app/src/models/InventoryValue.ts
Labels: korbit-code-analysis

#973 [ON-2853] restore scope 3 for basic+
  app/src/util/constants.ts
Labels: korbit-code-analysis

#972 [ON-2881] fix deletion of cities with invites
  app/migrations/20241211143647-cityInvite_delete_cascade.cjs
Labels: korbit-code-analysis

#974 [ON-3116] fix translations on "inventory created" page
  app/src/i18n/locales/de/onboarding.json
  app/src/i18n/locales/es/onboarding.json
  app/src/i18n/locales/pt/onboarding.json
Labels: korbit-code-analysis

#970 fix: add ON DELETE CASCADE to foreign key of GasValue
  app/migrations/20241210173228-gasvalue-activityvalue-on-delete-cascade.cjs
Labels: korbit-code-analysis

#975 feat: translate Basic+ Manual Input; closes ON-2829
  app/src/i18n/locales/en/data.json
  app/src/util/form-schema/manual-input-hierarchy.json
Labels: korbit-code-analysis

#977 fix: translations for password rules; closes ON-3007
  app/src/i18n/locales/es/auth.json
  app/src/i18n/locales/pt/auth.json
Labels: korbit-code-analysis

#978 ON-3073 sector percentages fix for basic+
  app/src/backend/InventoryProgressService.ts
  app/src/backend/ResultsService.ts
  app/src/models/InventoryValue.ts
Labels: korbit-code-analysis

#981 Extra industry types and names
  app/src/backend/ResultsService.ts
  app/src/models/InventoryValue.ts
  app/src/util/form-schema/manual-input-hierarchy.json
Labels: korbit-code-analysis

#982 fix(ui): adds condition to show na for zero values
  app/src/app/[lng]/[inventory]/InventoryResultTab/EmissionBySectorTable.tsx
Labels: bug, ui, korbit-code-analysis

#983 fix: adds missing data source to waste and wastewater
  app/src/util/form-schema/manual-input-hierarchy.json
Labels: bug, ui, korbit-code-analysis

#984 [ON-3126] hide breakdown by activity
  app/src/app/[lng]/[inventory]/InventoryResultTab/ByScopeView.tsx
  app/src/app/[lng]/[inventory]/InventoryResultTab/index.tsx
  app/src/backend/ResultsService.ts
  app/src/util/types.ts
Labels: korbit-code-analysis

#988 [ON-3037] fix total emissions view For Scopes 4 and 5
  app/src/components/SegmentedProgress.tsx
Labels: korbit-code-analysis

#991 Fix/replace arrow icon with heat icon
  app/src/app/[lng]/[inventory]/InventoryResultTab/EmissionsWidget.tsx
  app/src/components/icons.tsx
Labels: bug, ui

#989 fix(api): ON-3122 prevent duplicate InventoryValues
  app/src/backend/ActivityService.ts
Labels: bug, api

#992 fix(ui): adds transalation to inventory year component
  app/src/components/Cards/years-selection-card.tsx
  app/src/i18n/locales/de/dashboard.json
  app/src/i18n/locales/en/dashboard.json
  app/src/i18n/locales/es/dashboard.json
  app/src/i18n/locales/pt/dashboard.json
Labels: bug, ui

#990 fix(api): don't return a 404 error when no emissions factors are found
  app/src/app/api/v0/emissions-factor/route.ts
Labels: enhancement, api

#1001 fix(ui, api): ON-3035 show based on previous year as N/A
  app/src/app/[lng]/[inventory]/InventoryResultTab/EmissionBySectorTable.tsx
  app/src/app/[lng]/[inventory]/InventoryResultTab/index.tsx
  app/src/backend/ActivityService.ts
  app/src/components/HomePage/TabHeader.tsx
Labels: bug, api, ui

#1008 fix(ui): properly update inventory total and other caches
  app/src/services/api.ts
Labels: bug, ui

#1010 fix(ui): crash on public dashboard when targetYears wasn't loaded yet
  app/src/app/[lng]/[inventory]/InventoryResultTab/index.tsx
  app/src/util/helpers.ts
Labels: bug, ui

#1017 fix(ui): translate chat translations into supported languages
  app/src/components/ChatBot/chat-bot.tsx
  app/src/i18n/locales/de/chat.json
  app/src/i18n/locales/en/chat.json
  app/src/i18n/locales/es/chat.json
  app/src/i18n/locales/pt/chat.json
Labels: bug, ui

#1019 Fix/add missing translation functions to onboarding
  app/src/app/[lng]/onboarding/setup/page.tsx
  app/src/components/steps/add-inventory-details-step.tsx
  app/src/components/steps/select-city-steps.tsx
  app/src/i18n/locales/de/onboarding.json
  app/src/i18n/locales/en/onboarding.json
  app/src/i18n/locales/es/onboarding.json
  app/src/i18n/locales/pt/onboarding.json
Labels: bug, ui
