Repository Open-Earth-Foundation/CityCatalyst, pull requests merged in 2024-09, with the labels that each got.

#682 Update data.json
  app/src/i18n/locales/es/data.json
Labels: translation

#684 Manual input validation
  .DS_Store
  app/e2e/manual-input.spec.ts
  app/package-lock.json
  app/package.json
  app/src/app/[lng]/[inventory]/data/[step]/[subsector]/page.tsx
  app/src/app/[lng]/[inventory]/data/[step]/page.tsx
  app/src/app/[lng]/[inventory]/settings/page.tsx
  app/src/app/api/v0/inventory/[inventory]/activity-value/route.ts
  app/src/app/api/v0/inventory/[inventory]/value/subsector/[subsector]/route.ts
  app/src/backend/ActivityService.ts
  app/src/backend/CDPService.ts
  app/src/backend/CalculationService.ts
  app/src/backend/ManualnputValidationService.ts
  app/src/backend/NotificationService.ts
  app/src/components/Cards/add-data-card.tsx
  app/src/components/Cards/methodology-card.tsx
  app/src/components/Modals/activity-modal/activity-form-modal.tsx
  app/src/components/Modals/activity-modal/activity-modal-body.tsx
  app/src/components/Modals/delete-activity-modal.tsx
  app/src/components/Tabs/Activity/activity-tab.tsx
  app/src/components/Tabs/Activity/direct-measure-table.tsx
  app/src/components/building-select-input.tsx
  app/src/hooks/activity-value-form/use-activity-form.ts
  app/src/hooks/activity-value-form/use-activity-validation.tsx
  app/src/i18n/locales/en/data.json
  app/src/lib/custom-errors/manual-input-error.ts
  app/src/services/api.ts
  app/src/util/api.ts
  app/src/util/form-schema/index.ts
  app/src/util/form-schema/manual-input-hierarchy.json
  app/tailwind.config.cjs
  app/tests/api/activity_value.test.ts
Labels: javascript, api, ui

#690 Saving and Loading for activity based methodologies
  app/src/components/Modals/activity-modal/activity-modal-body.tsx
  app/src/components/Tabs/Activity/activity-accordion.tsx
  app/src/components/Tabs/Activity/activity-tab.tsx
  app/src/components/Tabs/Activity/direct-measure-table.tsx
Labels: javascript, ui

#685 feat(api): implement methodology formulas for methane commitment and VKT-1
  app/src/backend/CalculationService.ts
  app/src/backend/formulas.ts
Labels: enhancement, refactoring, api

#681 feat: added new route for modelled global-api structure
  global-api/main.py
  global-api/migrations/versions/1d9bbf3aff0e_create_modelled_schema.py
  global-api/routes/v1_emissions.py
Labels: enhancement, python, refactoring

#694 fix(api): gas formula calculation error
  app/src/backend/ActivityService.ts
  app/src/backend/CalculationService.ts
  app/src/backend/formulas.ts
Labels: bug, javascript, api

#709 Hide Methodology Selection page
  app/src/app/[lng]/[inventory]/data/[step]/[subsector]/page.tsx
  app/src/app/api/v0/inventory/[inventory]/activity-value/route.ts
  app/src/backend/ActivityService.ts
  app/src/components/Modals/change-methodology.tsx
  app/src/components/Tabs/Activity/activity-tab.tsx
  app/src/components/Tabs/Activity/emission-data-section.tsx
  app/src/components/Tabs/Activity/select-methodology.tsx
  app/src/i18n/locales/en/data.json
  app/src/services/api.ts
  app/src/util/form-schema/index.ts
Labels: javascript, api, ui

#706 Move global API specific ignore settings into global-api/.gitignore
  .gitignore
  global-api/.gitignore
Labels: python, refactoring

#727 Fixes for PR 726
  app/src/app/[lng]/[inventory]/InventoryResultTab/TopEmissionsWidget.tsx
  app/src/backend/ResultsService.ts
  app/src/lib/app-theme.ts
Labels: javascript, api, ui

#739 Fix/prefill extra field
  app/src/components/Modals/activity-modal/activity-modal-body.tsx
  app/src/components/MultiSelectInput.tsx
  app/src/components/Tabs/Activity/emission-data-section.tsx
  app/src/components/building-select-input.tsx
Labels: bug
