Repository Open-Earth-Foundation/CityCatalyst, pull requests merged in 2024-10, with the labels that each got.

#768 Feat/add link to learning hub
  app/src/components/navigation-bar.tsx
  app/src/i18n/locales/de/navigation.json
  app/src/i18n/locales/en/navigation.json
  app/src/i18n/locales/es/navigation.json
  app/src/i18n/locales/pt/navigation.json
Labels: enhancement

#765 feat(ui): adds component and library to render markdown response
  app/package-lock.json
  app/package.json
  app/src/components/ChatBot/chat-bot.tsx
Labels: enhancement

#761 fix: changes zindex value of the missing inventory component
  app/src/components/missing-inventory.tsx
Labels: bug

#696 feat(seed): ON-2204 Add emissions factors for transportation sector
  app/seed-data/emissions_factors/data_processed/ghgprotocol/DataSource.csv
  app/seed-data/emissions_factors/data_processed/ghgprotocol/DataSourceEmissionsFactor.csv
  app/seed-data/emissions_factors/data_processed/ghgprotocol/EmissionsFactor.csv
  app/seed-data/emissions_factors/data_processed/ghgprotocol/Methodology.csv
  app/seed-data/emissions_factors/data_processed/ghgprotocol/Publisher.csv
  app/seed-data/emissions_factors/data_raw/ghgprotocol/Emission_Factors_for_Cross_Sector_Tools_V2.0_0.xlsx
  app/seed-data/emissions_factors/scripts/ghgprotocol_transportation.py
Labels: python

#782 fix: waste default values
  .DS_Store
  app/seed-data/formula_values/data_processed/EFDB_2006_IPCC_guidelines/DataSourceFormulaInput.csv
  app/seed-data/formula_values/data_processed/EFDB_2006_IPCC_guidelines/FormulaInputs.csv
  app/seed-data/formula_values/data_processed/EFDB_2006_IPCC_guidelines/Methodology.csv
  app/seed-data/formula_values/scripts/EFDB_IPCC_Waste.py
Labels: data

#781 Fix/climate assistant proportions
  app/src/components/ChatBot/chat-popover.tsx
Labels: bug

#783 Fix/persist language in cookie
  app/src/components/navigation-bar.tsx
  app/src/middleware.ts
Labels: bug

#814 fix(ui): removes fixed height from climate assistant that caused overflow
  app/src/components/ChatBot/chat-popover.tsx
Labels: bug

#815 feat(e2e): add clear test matching case to Playwright config and add Playwright as recommended VS Code extension
  app/.vscode/extensions.json
  app/playwright.config.ts
Labels: javascript, tooling, e2e

#818 Feat/add unit tests for formulas
  app/package.json
  app/tests/api/activity_value.jest.ts
  app/tests/api/activity_value_data.ts
Labels: testing

#822 Fix/hide help link
  app/src/components/Sections/Footer.tsx
  app/src/components/navigation-bar.tsx
Labels: ui

#821 fix(ui): adds missing links to quick access links in the footer section
  app/src/components/Sections/Footer.tsx
Labels: bug

#824 fix(ui): replace portugal flag icon with brazil flag
  app/src/components/navigation-bar.tsx
Labels: refactoring, ui

#823 feat(ui): adds missing read the docs link to footer
  app/src/components/Sections/Footer.tsx
Labels: bug, ui

#840 Feat/add ask ai to button
  app/src/components/ChatBot/chat-popover.tsx
  app/src/components/icons.tsx
  app/src/i18n/locales/en/chat.json
  app/src/i18n/locales/es/chat.json
  app/src/i18n/locales/pt/chat.json
Labels: ui

#841 Fix/bring climate advisor to front
  app/src/components/ChatBot/chat-popover.tsx
Labels: bug, ui

#860 Feat/add abort action to chat assistant
  app/src/app/api/v0/assistants/threads/messages/route.ts
  app/src/components/ChatBot/chat-bot.tsx
  app/src/components/ChatBot/chat-popover.tsx
  app/src/i18n/locales/en/chat.json
Labels: enhancement, ui
