Repository Open-Earth-Foundation/CityCatalyst, pull requests merged in 2024-04, with the labels that each got.

#415 Fix/page navigation and routing
  app/src/app/[lng]/page.tsx
  app/src/i18n/locales/de/root-page.json
  app/src/i18n/locales/en/root-page.json
  app/src/i18n/locales/es/root-page.json
Labels: bug, enhancement

#417 fix(ui): empty dashboard, add data finish button not linking to dashboard, signup callback URL issue
  app/src/app/[lng]/[inventory]/data/review/page.tsx
  app/src/app/[lng]/[inventory]/page.tsx
  app/src/app/[lng]/auth/login/page.tsx
  app/src/app/[lng]/auth/signup/page.tsx
  app/src/components/Cards/SectorCard.tsx
Labels: bug

#419 Fix/user file error
  app/src/app/[lng]/[inventory]/settings/page.tsx
Labels: bug

#420 fix(ui): crash on add data page because file had no subsectors assigned
  app/src/app/[lng]/[inventory]/data/[step]/page.tsx
  app/src/features/city/inventoryDataSlice.ts
Labels: bug

#428 fix(db): not being able to disconnect source because of incorrect foreign key constraints
  app/migrations/20240408115847-inventory-value-cascade.cjs
Labels: bug

#429 feat(ui): show progress indicator for unfinished subsectors in list
  app/src/app/[lng]/[inventory]/data/[step]/page.tsx
  app/src/app/[lng]/[inventory]/data/[step]/types.d.ts
Labels: enhancement

#421 fix(api): population missing error for IEA source
  app/src/app/[lng]/onboarding/setup/page.tsx
  app/src/app/api/v0/datasource/[inventoryId]/route.ts
  app/src/util/helpers.ts
Labels: bug

#413 fix(ui): disconnecting source progress indicator being enabled for all sources
  app/src/app/[lng]/[inventory]/data/[step]/page.tsx
Labels: bug

#431 fix(ui): Replaces hard coded year with inventory year value
  app/src/app/[lng]/[inventory]/data/review/page.tsx
Labels: bug

#439 Fix/show population values
  app/src/app/[lng]/[inventory]/page.tsx
  app/src/app/api/v0/city/[city]/population/[year]/route.ts
  app/src/util/helpers.ts
Labels: bug

#445 fix(ui): show right flag for city
  app/src/app/[lng]/[inventory]/settings/page.tsx
  app/src/components/Tabs/my-files-tab.tsx
Labels: bug

#446 Fix/area not showing
  app/src/app/[lng]/[inventory]/page.tsx
  app/src/app/[lng]/onboarding/setup/page.tsx
  app/src/app/api/v0/city/[city]/boundary/route.ts
  app/src/services/api.ts
Labels: bug

#447 fix(ui): manual input form state errors
  app/src/app/[lng]/[inventory]/data/[step]/SubsectorDrawer.tsx
Labels: bug

#457 fix(ui): save uploaded file to database immediately
  app/src/app/[lng]/[inventory]/data/[step]/page.tsx
  app/src/components/Modals/add-file-data-modal.tsx
  app/src/components/Modals/delete-file-modal.tsx
  app/src/features/city/inventoryDataSlice.ts
  app/src/i18n/locales/en/data.json
Labels: bug

#463 fix(ui): redirecting unauthenticated users to login page
  app/src/app/[lng]/[inventory]/page.tsx
  app/src/app/[lng]/page.tsx
  app/src/util/check-user-session.ts
Labels: bug
