Repository Open-Earth-Foundation/CityCatalyst, pull requests merged in 2024-08, with the labels that each got.

#607 Manual input formulas & saving
  app/migrations/20240805110810-activity-value-co2eq.cjs
  app/src/app/api/v0/inventory/[inventory]/activity-value/[id]/route.ts
  app/src/app/api/v0/inventory/[inventory]/activity-value/route.ts
  app/src/app/api/v0/inventory/[inventory]/value/[subcategory]/route.ts
  app/src/backend/CalculationService.ts
  app/src/models/ActivityValue.ts
  app/tests/api/inventory.test.ts
Labels: enhancement, javascript, api

#624 Feature/restore direct measure
  app/src/app/[lng]/[inventory]/data/[step]/[subsector]/page.tsx
  app/src/components/Cards/methodology-card.tsx
  app/src/components/Modals/add-activity-modal.tsx
  app/src/components/Tabs/Activity/activity-tab.tsx
  app/src/util/form-schema/index.ts
  app/src/util/form-schema/manual-input-hierarchy.json
Labels: enhancement

#646 use i18n version of the catalogue
  app/migrations/20240809141227-create-datasourceI18n.cjs
  app/migrations/20240809142521-prefill-datasource.cjs
  app/migrations/20240812130411-adjust-fk.cjs
  app/scripts/catalogue-sync.ts
  app/seeders/20231114094254-emissions-factors.cjs
  app/src/app/[lng]/[inventory]/data/[step]/ActivityDataTab.tsx
  app/src/app/[lng]/[inventory]/data/[step]/SourceDrawer.tsx
  app/src/app/[lng]/[inventory]/data/[step]/page.tsx
  app/src/app/[lng]/[inventory]/data/[step]/types.d.ts
  app/src/app/api/v0/datasource/[inventoryId]/[sectorId]/route.ts
  app/src/app/api/v0/datasource/[inventoryId]/route.ts
  app/src/app/api/v0/inventory/[inventory]/route.ts
  app/src/backend/ActivityService.ts
  app/src/backend/DataSourceService.ts
  app/src/components/Modals/add-activity-modal.tsx
  app/src/i18n/index.ts
  app/src/models/ActivityData.ts
  app/src/models/ActivityValue.ts
  app/src/models/DataSourceActivityData.ts
  app/src/models/DataSourceEmissionsFactor.ts
  app/src/models/DataSourceGHGs.ts
  app/src/models/DataSourceI18n.ts
  app/src/models/DataSourceMethodology.ts
  app/src/models/DataSourceReportingLevel.ts
  app/src/models/DataSourceScope.ts
  app/src/models/EmissionsFactor.ts
  app/src/models/GDP.ts
  app/src/models/GHGs.ts
  app/src/models/InventoryValue.ts
  app/src/models/Methodology.ts
  app/src/models/Population.ts
  app/src/models/Publisher.ts
  app/src/models/ReportingLevel.ts
  app/src/models/Scope.ts
  app/src/models/Sector.ts
  app/src/models/SubCategory.ts
  app/src/models/SubSector.ts
  app/src/models/init-models.ts
  app/src/util/helpers.ts
  app/src/util/types.d.ts
  app/tests/api/datasource.test.ts
  app/tests/api/inventory.test.ts
Labels: javascript, database

#655 Load manual input hierarchy JSON file and search for methodology ID to get formula in CalculationService
  app/src/backend/CalculationService.ts
  app/src/util/form-schema/index.ts
Labels: enhancement, api

#654 Feat(UI): Saving and loading direct measure emissions data
  app/src/app/[lng]/[inventory]/data/[step]/[subsector]/page.tsx
  app/src/app/[lng]/[inventory]/page.tsx
  app/src/components/Modals/add-activity-modal.tsx
  app/src/components/Tabs/Activity/activity-accordion.tsx
  app/src/components/Tabs/Activity/activity-tab.tsx
  app/src/components/Tabs/Activity/direct-measure-table.tsx
  app/src/components/building-select-input.tsx
  app/src/components/icons.tsx
  app/src/i18n/locales/en/data.json
  app/src/lib/app-theme.ts
  app/src/services/api.ts
  app/src/util/helpers.ts
Labels: bug, enhancement

#652 feat:EF for I.7.1 and I.8.1
  app/seed-data/emissions_factors/data_processed/EFDB_2006_IPCC_guidelines/DataSourceEmissionsFactor.csv
  app/seed-data/emissions_factors/data_processed/EFDB_2006_IPCC_guidelines/EmissionsFactor.csv
  app/seed-data/emissions_factors/scripts/EFDB_2006_IPCC_guidelines_Stationary_Energy.py
Labels: python

#663 refactor(test): remove cypress devDependency and files
  app/cypress/fixtures/example.json
  app/cypress/support/commands.ts
  app/cypress/support/e2e.ts
  app/cypress/tsconfig.json
  app/package-lock.json
  app/package.json
  app/tsconfig.json
Labels: javascript, refactoring

#669 fix: adds target property to open page gpc protocal page in different tab
  app/src/components/Tabs/Activity/activity-tab.tsx
Labels: bug

#665 remove transaction
  app/migrations/20240812130411-adjust-fk.cjs
Labels: javascript, refactoring, api

#662 Filter emissions factors in the backend
  app/package-lock.json
  app/package.json
  app/seeders/20231114094254-emissions-factors.cjs
  app/src/app/[lng]/[inventory]/data/[step]/SubsectorDrawer.tsx
  app/src/app/[lng]/[inventory]/data/[step]/page.tsx
  app/src/app/api/v0/emissions-factor/route.ts
  app/src/components/Modals/add-activity-modal.tsx
  app/src/models/EmissionsFactor.ts
  app/src/models/Methodology.ts
  app/src/models/init-models.ts
  app/src/services/api.ts
Labels: enhancement, javascript, api
