Repository Open-Earth-Foundation/CityCatalyst, pull requests merged in 2025-01, with the labels that each got.

#1052 fix(test): mock methods not being called for GlobalAPIService
  app/src/backend/GlobalAPIService.ts
  app/src/backend/ResultsService.ts
  app/tests/api/emissions_forecast.jest.ts
Labels: api, testing

#1070 fix: adds form tags, is loading state to modal
  app/src/components/Modals/delete-inventory-modal.tsx
Labels: bug, ui

#1071 fix: adds better token verification error handling
  app/src/app/api/v0/auth/password/route.ts
Labels: bug
