Repository Open-Earth-Foundation/CityCatalyst, pull requests merged in 2025-08, with the labels that each got.

#1649 fix: adds mission translations for toast error message
  app/src/i18n/locales/de/manage-subsectors.json
  app/src/i18n/locales/en/manage-subsectors.json
  app/src/i18n/locales/es/manage-subsectors.json
  app/src/i18n/locales/fr/manage-subsectors.json
  app/src/i18n/locales/pt/manage-subsectors.json
Labels: Visual bug, i18n

#1720 fix: JN actions buttons visual styling
  app/src/components/HomePageJN/ActionCardSmall.tsx
  app/src/components/HomePageJN/ActionCards.tsx
  app/src/components/HomePageJN/AddCollaboratorButton.tsx
  app/src/components/icons.tsx
Labels: ui, Visual bug

#1735 Fix missing Spanish translation for role in admin team page
  app/src/i18n/locales/en/admin.json
  app/src/i18n/locales/es/admin.json
Labels: codex

#1732 fix: ON-4358 - "Project" appears in English when creating inventory
  app/src/i18n/locales/de/onboarding.json
  app/src/i18n/locales/en/onboarding.json
  app/src/i18n/locales/es/onboarding.json
  app/src/i18n/locales/fr/onboarding.json
  app/src/i18n/locales/pt/onboarding.json
Labels: codex

#1758 ON-4355 - Symbol appears on “Download city data”
  app/src/components/Tabs/MyProfileTab/ManageCitiesTabPanel.tsx
Labels: codex
